### PR TITLE
Support describe modes from git-prompt.sh

### PR DESCRIPTION
**Pull request by mjg**
contrib/completion/git-prompt.sh has various GIT_PS1_DESCRIBE_STYLEs for
describing the current HEAD.

Implement all these modes in addition to the existing one.

### CODE REVIEW

**Comment by mjg** [comment]
It appears that Github updates the PR whenever I update the master branch. That was not my intention, sorry.

Only the first commit (865c08f) works with current git. The next one will work with the next release, and the last one is pending submission. This PR is only about the first.

**Comment by cowboy** [comment]
> It appears that Github updates the PR whenever I update the master branch. That was not my intention, sorry.

@mjg you could create a branch containing just the commit(s) you care about and update the PR to use that branch!

**Comment by svscorp** [comment]
It is a good feature. I realized that PR is not merged in a while trying to enable it in arguments :)

Any chances it will be reviewed / merged?

**Comment by jcharaoui** [comment]
Thank you for your contribution. I tested it and it does seem like a useful feature.

Since the PR contains an extraneous commit, I can't merge the PR directly so I just went ahead and cherry-picked the commits from your fork in 9eeadb2cfbd026b4954d80719d02db2e5c906cdf and dd2e95fa88675383958a44c340452e2f0a582632.

**Comment by mjg** [comment]
Oh, thanks. I didn't notice there's still interest. The extra commit was using a feature that was not released in git (master) back then, I'm running git with a few additions on top; not all of them make it to git.git eventually. I have to recheck the current state of git in-progress info before I opem a new PR for that.

**Pull request closed without merging**
